version: "1"
rules:
  - base: master
    upstream: biscuitdevelopment:master
  - base: development
    upstream: biscuitdevelopment:development
  - base: automatic-build
    upstream: biscuitdevelopment:development