version: "1"
rules:
  - base: master
    upstream: biscuitdevelopment:master
    mergeMethod: rebase
  - base: development
    upstream: biscuitdevelopment:development
    mergeMethod: rebase
  - base: automatic-build
    upstream: biscuitdevelopment:development
    mergeMethod: rebase
