name: Sync with upstream

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to sync with upstream'
        required: true
        default: 'development'

jobs:
  sync:
    name: Sync with upstream
    runs-on: ubuntu-latest
    steps:
      - name: Add remotes
        run: "git remote add upstream https://github.com/BiscuitDevelopment/SkyblockAddons.git"
      - name: Fetch upstream
        run: git fetch upstream
      - name: Get git-rebase-all executable
        run: "wget https://raw.githubusercontent.com/nornagon/git-rebase-all/master/git-rebase-all"
      - name: Setup all tracking branches
        if: github.event_name != 'workflow_dispatch'
        run: "upstream=upstream ; for branch_name in `git branch -r | grep $upstream | grep -v master | grep -v HEAD | sed -e 's/.*\\///g'`; do git branch --track $branch_name  $upstream/$branch_name ; done"
      - name: Setup single tracking branch
        if: github.event_name == 'workflow_dispatch'
        run: "git branch --track ${{ github.event.inputs.branch }}  $upstream/${{ github.event.inputs.branch }}"
      - name: Rebase tracked branches
        run: "git pull --rebase --all"
      - name: Push all changes
        run: "git push --all origin"